---
- name: Check if Apache is running
  command: systemctl status httpd
  ignore_errors: true
  register: apache_status
  changed_when: False

- name: Debug Apache running status
  debug:
    msg: "Apache status checked. Running: {{ apache_status.rc == 0 }}"

- name: Start Apache if it's not running
  command: systemctl start httpd
  when: apache_status.rc != 0

- name: Debug Apache started
  debug:
    msg: "Apache started."
  when: apache_status.rc != 0

- name: Stop Apache if it's running
  command: systemctl stop httpd
  when: apache_status.rc == 0

- name: Debug Apache stopped
  debug:
    msg: "Apache stopped."
  when: apache_status.rc == 0
