---
- name: Check if Apache is running
  command: systemctl status httpd
  ignore_errors: true
  register: apache_status
  changed_when: False
  failed_when: 
    - apache_status.rc == 0
    - '"active (running)" not in apache_status.stdout'

- name: Debug Apache running status
  debug:
    msg: "Apache is currently not running."
  when: apache_status.rc != 0

- name: Stop Apache if it's running
  command: systemctl stop httpd
  when: apache_status.rc == 0

- name: Debug Apache stopped
  debug:
    msg: "Apache has been stopped."
  when: apache_status.rc == 0
